### ISSUE TITLE
ShapeNet dataset questions

### ISSUE THREAD

**Issue by stalkerrush** [chenhsuanlin/signed-distance-SRN#2]
Hi @chenhsuanlin , thanks for releasing this great work! I'm reading your code and the camera rotation augmentation doesn't quite make sense to me [here](https://github.com/chenhsuanlin/signed-distance-SRN/blob/ead13c0a63253489fed7731cecea0d737b72161d/data/shapenet.py#L143). Why is the rotation over X axis instead of Z axis? 
Also another quick question about data: I remember there are 100000 points for evaluation in like DVR. It seems that you created a pointcloud3.npz containing 30000 points by excluding interior. But you still sample 100000 on the predicted mesh. Can you briefly elaborate on why you use a different number of samples (yours vs DVR & your gt vs your pred)?

Thank you!

**Comment by chenhsuanlin** [comment]
1. The provided ShapeNet camera matrices define x as the axis pointing towards the camera (in the camera frame coordinates), so that's why it's the X axis for ShapeNet but Z for PASCAL3D+. This shouldn't matter at the moment either, as I didn't turn on random in-plane rotation augmentation in any of the experiments.
2. I chose to sample 100K points following prior practice (DVR), but this affects the Chamfer distance results very little as 30K or 100K points are both very dense already.

Hope this helps!

**Comment by stalkerrush** [comment]
Thanks that helps a lot. For the axis, I think when you created the [pose_cam](https://github.com/chenhsuanlin/signed-distance-SRN/blob/ead13c0a63253489fed7731cecea0d737b72161d/data/shapenet.py#L63), the translation is over Z right?

**Comment by chenhsuanlin** [comment]
Yes, the translation in `pose_cam` is on the Z axis.
I double-checked and realized that the rotation augmentation should be around the Z axis for ShapeNet as well. I think I got mixed up with an older version of ShapeNet I used to have. This is now corrected in the latest commit. Thanks for spotting it!

**Comment by stalkerrush** [comment]
Thanks for double-checking this. Another quick question regarding mesh visualization: when I load the dumped mesh with Trimesh and show it, the visualized mesh seems to be only showing the invisible part instead of the visible part. I need to toggle backface culling to visualize it correctly. Is this expected? I'm not very familiar with graphics but it seems I don't need to do this in other repos like DVR.

**Comment by chenhsuanlin** [comment]
I'm not sure how Trimesh behaves. Did you have to toggle backface culling for all the dumped meshes?
I've been using Blender and other preview softwares to visualize the meshes and they seemed fine, I didn't have to do backface culling in particular. My one guess is because of different winding orders between Trimesh and [PyMCubes](https://github.com/pmneila/PyMCubes) (which I used for isosurface extraction), which might be automatically handled by Blender.
I'll reopen this issue for now until this is resolved.

**Comment by stalkerrush** [comment]
Yes. Blender also works for me without backface culling. It seems the winding order is the answer. I permuted the 2nd column and the 3rd column of the faces before feeding into Trimesh then it looks normal. Thanks!
