### ISSUE TITLE
Rendering script for shapenet

### ISSUE THREAD

**Issue by mj-hue** [chenhsuanlin/signed-distance-SRN#4]
Hello, is that possible for you to share the rendering script of shapenet inputs and the generation script for pointcloud? Thank you.

**Comment by chenhsuanlin** [comment]
The RGB renderings of ShapeNet were taken from the [DVR](https://github.com/autonomousvision/differentiable_volumetric_rendering) repo. I can work on releasing the script for creating the ground-truth point clouds probably in a week or two -- leaving the issue open for now.

**Comment by mj-hue** [comment]
Thanks. It would help a lot for trying sdf-srn on more categories of shapenet if you can release the pointcloud code. Besides, it seems the train, val, test lists are generated as the intersection of shapenetv2 and DVR. Are there any reason not to directly use the DVR split?

**Comment by chenhsuanlin** [comment]
Sorry for the late reply. Initially I did want to stick with ShapeNet v2 because there were problems in v1 (e.g. corrupted CAD models). For the three categories in consideration here, the significant difference is just that half of the car CAD models were removed. For reasons of comparing and benchmarking against previous methods (whose train/val/test splits were based on v1), taking the intersection of the splits seems to be the more reasonable thing to do.
Hope this helps!

**Comment by chenhsuanlin** [comment]
I have uploaded the script and [README](https://github.com/chenhsuanlin/signed-distance-SRN/blob/main/data/README.md) for creating ground-truth point clouds for ShapeNet. Please let me know if you're interested in the script for PASCAL3D+.
Apologies for the wait! Please feel free to reopen the issue if you have further questions.
